import { yekan } from "@/utils/Font";
import "./globals.css";
import Layout from "@/layout/Layout";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authoptions } from "./api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import ButtonProvider from "@/context/ButtonContext";
import MenuProvider from "@/context/MenuContext";

export const metadata = {
  title: "Pizza Land",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authoptions);
  if (!session) redirect("/signin");

  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <ButtonProvider>
          <MenuProvider>
            <NextAuthProvider>
              <Layout>{children}</Layout>
            </NextAuthProvider>
          </MenuProvider>
        </ButtonProvider>
      </body>
    </html>
  );
}
